
    create table amendment (
       id_amendment int8 generated by default as identity,
        amendment_type varchar(255),
        reason varchar(255),
        remark varchar(255),
        primary key (id_amendment)
    );

    create table base_rccs (
       id_base_rccs int8 generated by default as identity,
        booking_charges_id_booking_charges int8,
        primary key (id_base_rccs)
    );

    create table bl_and_si_information (
       id_bl_and_si_information int8 generated by default as identity,
        bl_number varchar(255),
        esi_ref_number varchar(255),
        si_mode varchar(255),
        si_received_date_time varchar(255),
        line_items_id_line_items int8,
        primary key (id_bl_and_si_information)
    );

    create table bl_numbers (
       id_bl_numbers int8 generated by default as identity,
        bl_numbers varchar(255),
        booking_id_booking int8,
        primary key (id_bl_numbers)
    );

    create table booking (
       id_booking int8 generated by default as identity,
        booking_confirmation_date varchar(255),
        booking_creation_date varchar(255),
        booking_lbu varchar(255),
        booking_number varchar(255),
        booking_type varchar(255),
        booking_update_date varchar(255),
        brand varchar(255),
        contract_number varchar(255),
        contribution_margin_currency varchar(255),
        contribution_margin_total varchar(255),
        destination_service_type varchar(255),
        doc_cut_off varchar(255),
        has_dg_request_attachment boolean,
        im_approved_for_dg boolean,
        is_booking_split boolean,
        is_cod_performed boolean,
        is_commitment boolean,
        is_instant_booking boolean,
        is_pending_for_allocation boolean,
        is_pld_inbound boolean,
        is_por_cat boolean,
        is_por_inbound boolean,
        is_slot_booking boolean,
        is_split_allowed boolean,
        is_vessel_renominated boolean,
        origin_service_type varchar(255),
        responsible_lbu varchar(255),
        service_term varchar(255),
        station_code varchar(255),
        status varchar(255),
        trade varchar(255),
        booking_rad_id_booking_rad int8,
        booking_transport_plan_id_booking_transport_plan int8,
        doc_location_id_doc_location int8,
        pld_id_pld int8,
        pod_id_pod int8,
        pol_id_pol int8,
        por_id_por int8,
        primary key (id_booking)
    );

    create table booking_charges (
       id_booking_charges int8 generated by default as identity,
        booking_product_item_number varchar(255),
        charge_amount varchar(255),
        charge_basis varchar(255),
        charge_currency varchar(255),
        charge_item_number int4,
        charge_rate varchar(255),
        charge_type varchar(255),
        charge_unit varchar(255),
        formation_type varchar(255),
        is_bundled boolean,
        is_obsolete boolean,
        occuring_at varchar(255),
        prepaid_collect varchar(255),
        rcc varchar(255),
        tariff_amount varchar(255),
        tariff_currency varchar(255),
        tariff_rate varchar(255),
        booking_id_booking int8,
        primary key (id_booking_charges)
    );

    create table booking_commitments (
       id_booking_commitments int8 generated by default as identity,
        commitment_request_number varchar(255),
        booking_id_booking int8,
        primary key (id_booking_commitments)
    );

    create table booking_products (
       id_booking_products int8 generated by default as identity,
        booking_product_item_number varchar(255),
        booking_product_number varchar(255),
        cargo_type varchar(255),
        contract_number varchar(255),
        ebkg_commodity_description varchar(255),
        is_active boolean,
        shipment_type varchar(255),
        soc_coc varchar(255),
        trade_commodity_group varchar(255),
        booking_id_booking int8,
        primary key (id_booking_products)
    );

    create table booking_rad (
       id_booking_rad int8 generated by default as identity,
        overruled boolean,
        preliminary boolean,
        rad varchar(255),
        rad_type varchar(255),
        primary key (id_booking_rad)
    );

    create table booking_reference (
       id_booking_reference int8 generated by default as identity,
        booking_id_booking int8,
        primary key (id_booking_reference)
    );

    create table booking_transport_plan (
       id_booking_transport_plan int8 generated by default as identity,
        amendment_id_amendment int8,
        booking_id_booking int8,
        primary key (id_booking_transport_plan)
    );

    create table booking_vas (
       id_booking_vas int8 generated by default as identity,
        booking_products_id_booking_products int8,
        primary key (id_booking_vas)
    );

    create table business_partners (
       id_pusiness_partners int8 generated by default as identity,
        partner_fi_account varchar(255),
        partner_fi_account_territory varchar(255),
        partner_is_nac boolean,
        partner_number varchar(255),
        role varchar(255),
        booking_id_booking int8,
        primary key (id_pusiness_partners)
    );

    create table cargo_pkp_or_del (
       id_cargo_pkp_or_del int8 generated by default as identity,
        line_items_id_line_items int8,
        primary key (id_cargo_pkp_or_del)
    );

    create table commercial_vvd (
       id_commercial_vvd int8 generated by default as identity,
        direction varchar(255),
        voyage_number varchar(255),
        vessel_id_vessel int8,
        primary key (id_commercial_vvd)
    );

    create table dg_commodities (
       id_dg_commodities int8 generated by default as identity,
        line_items_id_line_items int8,
        primary key (id_dg_commodities)
    );

    create table doc_location (
       id_doc_location int8 generated by default as identity,
        number varchar(255),
        type varchar(255),
        primary key (id_doc_location)
    );

    create table equipment_seal_numbers (
       id_equipment_seal_numbers int8 generated by default as identity,
        equipment_seal_numbers varchar(255),
        line_items_id_line_items int8,
        primary key (id_equipment_seal_numbers)
    );

    create table facility (
       id_facility int8 generated by default as identity,
        number varchar(255),
        type varchar(255),
        primary key (id_facility)
    );

    create table invalidity_reason_codes (
       id_invalidity_reason_codes int8 generated by default as identity,
        legs_id_legs int8,
        primary key (id_invalidity_reason_codes)
    );

    create table leg_approvals (
       id_leg_approvals int8 generated by default as identity,
        legs_id_legs int8,
        primary key (id_leg_approvals)
    );

    create table leg_from (
       id_leg_from int8 generated by default as identity,
        number varchar(255),
        type varchar(255),
        primary key (id_leg_from)
    );

    create table legs (
       id_legs int8 generated by default as identity,
        availability_date_time varchar(255),
        bl_leg boolean,
        cut_off_date_time varchar(255),
        eta varchar(255),
        etd varchar(255),
        idle_time varchar(255),
        invalid_tp_leg_flag boolean,
        mode varchar(255),
        operation_type varchar(255),
        sequence_number varchar(255),
        total_transit_time varchar(255),
        transit_time varchar(255),
        vvd_facility_ident_figure_from varchar(255),
        vvd_facility_ident_figure_to varchar(255),
        booking_transport_plan_id_booking_transport_plan int8,
        commercialvvd_id_commercial_vvd int8,
        leg_from_id_leg_from int8,
        leg_to_id_leg_to int8,
        operational_from_facilityvvd_id_operational_from_facility_vvd int8,
        operational_to_facilityvvd_id_operational_to_facility_vvd int8,
        primary key (id_legs)
    );

    create table leg_to (
       id_leg_to int8 generated by default as identity,
        number varchar(255),
        type varchar(255),
        primary key (id_leg_to)
    );

    create table line_items (
       id_line_items int8 generated by default as identity,
        booking_line_item_number varchar(255),
        booking_line_item_status varchar(255),
        equipment_number varchar(255),
        equipment_size varchar(255),
        equipment_type varchar(255),
        gate_in_weight varchar(255),
        gross_weight varchar(255),
        is_equ_profile_auto_assigned varchar(255),
        is_equ_size_type_auto_substituted varchar(255),
        is_swap_happened varchar(255),
        iso_size_type varchar(255),
        tare_weight varchar(255),
        vgm varchar(255),
        vgm_provided_by_terminal varchar(255),
        booking_products_id_booking_products int8,
        primary key (id_line_items)
    );

    create table mrn_and_fda_details (
       id_mrn_and_fda_details int8 generated by default as identity,
        line_items_id_line_items int8,
        primary key (id_mrn_and_fda_details)
    );

    create table mty_pkp_or_del (
       id_mty_pkp_or_del int8 generated by default as identity,
        date_time varchar(255),
        ismtyrelease_not_required boolean,
        pkp_or_del varchar(255),
        facility_id_facility int8,
        line_items_id_line_items int8,
        primary key (id_mty_pkp_or_del)
    );

    create table operational_from_facility_vvd (
       id_operational_from_facility_vvd int8 generated by default as identity,
        direction varchar(255),
        voyage_number varchar(255),
        vessel_id_vessel int8,
        primary key (id_operational_from_facility_vvd)
    );

    create table operational_to_facility_vvd (
       id_operational_to_facility_vvd int8 generated by default as identity,
        direction varchar(255),
        voyage_number varchar(255),
        vessel_id_vessel int8,
        primary key (id_operational_to_facility_vvd)
    );

    create table pld (
       id_pld int8 generated by default as identity,
        number varchar(255),
        type varchar(255),
        primary key (id_pld)
    );

    create table pod (
       id_pod int8 generated by default as identity,
        number varchar(255),
        type varchar(255),
        primary key (id_pod)
    );

    create table pol (
       id_pol int8 generated by default as identity,
        number varchar(255),
        type varchar(255),
        primary key (id_pol)
    );

    create table por (
       id_por int8 generated by default as identity,
        number varchar(255),
        type varchar(255),
        primary key (id_por)
    );

    create table remarks (
       id_remarks int8 generated by default as identity,
        creation_date varchar(255),
        ebkg_additional_shipment_details boolean,
        reason_code varchar(255),
        reason_code_category varchar(255),
        remark varchar(255),
        booking_id_booking int8,
        primary key (id_remarks)
    );

    create table special_handling (
       id_special_handling int8 generated by default as identity,
        booking_products_id_booking_products int8,
        primary key (id_special_handling)
    );

    create table tariff_commodities (
       id_tariff_commodities int8 generated by default as identity,
        tariff_commodities varchar(255),
        booking_products_id_booking_products int8,
        primary key (id_tariff_commodities)
    );

    create table vessel (
       id_vessel int8 generated by default as identity,
        vessel_imo_number varchar(255),
        primary key (id_vessel)
    );

    alter table if exists base_rccs 
       add constraint FK2p7g0xi0jist6yigva3cq7hgl 
       foreign key (booking_charges_id_booking_charges) 
       references booking_charges;

    alter table if exists bl_and_si_information 
       add constraint FK1cutsbit9f5fvoorylmyqrr1l 
       foreign key (line_items_id_line_items) 
       references line_items;

    alter table if exists bl_numbers 
       add constraint FKpf7nyfq853ug19jl6diihtrcv 
       foreign key (booking_id_booking) 
       references booking;

    alter table if exists booking 
       add constraint FKk4vhjyo1m05qsife90x6j34ed 
       foreign key (booking_rad_id_booking_rad) 
       references booking_rad;

    alter table if exists booking 
       add constraint FK9jgjsxhrkghi1f5ba1ovciog9 
       foreign key (booking_transport_plan_id_booking_transport_plan) 
       references booking_transport_plan;

    alter table if exists booking 
       add constraint FKdbgac8acvr3wlwwcq5j9hpwi 
       foreign key (doc_location_id_doc_location) 
       references doc_location;

    alter table if exists booking 
       add constraint FKqx3h79b26nlm53ymso4bt3exc 
       foreign key (pld_id_pld) 
       references pld;

    alter table if exists booking 
       add constraint FK777s1sxo1kbo8ahuh4iq6pil9 
       foreign key (pod_id_pod) 
       references pod;

    alter table if exists booking 
       add constraint FKh9l18soqrdaq2t3yit34t3yyl 
       foreign key (pol_id_pol) 
       references pol;

    alter table if exists booking 
       add constraint FK1nox96qvx4icgmbnylhotq4d0 
       foreign key (por_id_por) 
       references por;

    alter table if exists booking_charges 
       add constraint FKkjq3vcby15luhv5lqnpdstc0a 
       foreign key (booking_id_booking) 
       references booking;

    alter table if exists booking_commitments 
       add constraint FKg9r3bjdif7339x36op5jaregw 
       foreign key (booking_id_booking) 
       references booking;

    alter table if exists booking_products 
       add constraint FKl7go1k7l6a8hyqgylo0qe6u1p 
       foreign key (booking_id_booking) 
       references booking;

    alter table if exists booking_reference 
       add constraint FKjf2kj2axso77472vh23ip5w4v 
       foreign key (booking_id_booking) 
       references booking;

    alter table if exists booking_transport_plan 
       add constraint FK6btbnsosi82n730i1mcnvvwes 
       foreign key (amendment_id_amendment) 
       references amendment;

    alter table if exists booking_transport_plan 
       add constraint FKaw2pb6nxh2cbj024hm9ka04da 
       foreign key (booking_id_booking) 
       references booking;

    alter table if exists booking_vas 
       add constraint FKfb614lxlgvnkbc2ym4ap4imad 
       foreign key (booking_products_id_booking_products) 
       references booking_products;

    alter table if exists business_partners 
       add constraint FKcgr852v9e4q9ivwcrwuxaa684 
       foreign key (booking_id_booking) 
       references booking;

    alter table if exists cargo_pkp_or_del 
       add constraint FK3b5dfwtfjp2s3irhglnx4wvo2 
       foreign key (line_items_id_line_items) 
       references line_items;

    alter table if exists commercial_vvd 
       add constraint FKssw1o1vykja63b3idas8k5sd3 
       foreign key (vessel_id_vessel) 
       references vessel;

    alter table if exists dg_commodities 
       add constraint FKs9fyt4et98jtep8bf6ajqb5lk 
       foreign key (line_items_id_line_items) 
       references line_items;

    alter table if exists equipment_seal_numbers 
       add constraint FKlgk19daf0ayq1v1aaqdcj0nm7 
       foreign key (line_items_id_line_items) 
       references line_items;

    alter table if exists invalidity_reason_codes 
       add constraint FK39aso1q25hcy0d53s4wno7xyt 
       foreign key (legs_id_legs) 
       references legs;

    alter table if exists leg_approvals 
       add constraint FK2x08rmibq4qrvok9kjkq0bwxy 
       foreign key (legs_id_legs) 
       references legs;

    alter table if exists legs 
       add constraint FK9rvuel3u5b11dhs2wwgylu1t3 
       foreign key (booking_transport_plan_id_booking_transport_plan) 
       references booking_transport_plan;

    alter table if exists legs 
       add constraint FK80jkjs2xucmyji618inu6y26t 
       foreign key (commercialvvd_id_commercial_vvd) 
       references commercial_vvd;

    alter table if exists legs 
       add constraint FKrxuoc8xa66fvj093upr885v2s 
       foreign key (leg_from_id_leg_from) 
       references leg_from;

    alter table if exists legs 
       add constraint FKhytc94qgc5d9j6pii8c8mwiws 
       foreign key (leg_to_id_leg_to) 
       references leg_to;

    alter table if exists legs 
       add constraint FKf2jwvp3ab5alute507k7h42kg 
       foreign key (operational_from_facilityvvd_id_operational_from_facility_vvd) 
       references operational_from_facility_vvd;

    alter table if exists legs 
       add constraint FKrddila0yjkphx42icqiay6cab 
       foreign key (operational_to_facilityvvd_id_operational_to_facility_vvd) 
       references operational_to_facility_vvd;

    alter table if exists line_items 
       add constraint FK2rfswb2bernd24tc5ufe0lraw 
       foreign key (booking_products_id_booking_products) 
       references booking_products;

    alter table if exists mrn_and_fda_details 
       add constraint FKrh4e0cyfrl9nds7qlx02c0scf 
       foreign key (line_items_id_line_items) 
       references line_items;

    alter table if exists mty_pkp_or_del 
       add constraint FK5f4becpq3bbi1c4tome3kljpg 
       foreign key (facility_id_facility) 
       references facility;

    alter table if exists mty_pkp_or_del 
       add constraint FKoh62x0cmgcm61jmapgk29qlw8 
       foreign key (line_items_id_line_items) 
       references line_items;

    alter table if exists operational_from_facility_vvd 
       add constraint FKadd0s4950pw0vgf773lft2dls 
       foreign key (vessel_id_vessel) 
       references vessel;

    alter table if exists operational_to_facility_vvd 
       add constraint FK5p95rly50ueka7k7bakt5dvde 
       foreign key (vessel_id_vessel) 
       references vessel;

    alter table if exists remarks 
       add constraint FKs0ecks8a7ue0ux1cqp8jl0bem 
       foreign key (booking_id_booking) 
       references booking;

    alter table if exists special_handling 
       add constraint FK17o2j22tu5ajn7h8m4wf9trkc 
       foreign key (booking_products_id_booking_products) 
       references booking_products;

    alter table if exists tariff_commodities 
       add constraint FK4crjoetyu74jjevj4a6cacahy 
       foreign key (booking_products_id_booking_products) 
       references booking_products;
